runtime: nodejs16
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: client/build/\1
    upload: client/build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html