runtime: python38

handlers:
# frontend
- url: /static
  static_dir: build/static
- url: /(.*\.(json|ico|js|html))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js|html)$

# backend
- url: /.*
  script: auto